import React from 'react';
import {getRndInteger} from '../utils/utilityFunctions';

class InstructionsLM extends React.Component {
    constructor(props) {
        super(props); 
    }
    
    componentDidMount() {
        this._fetchQuoteAndDisplay(); 
    }

    async _fetchQuoteAndDisplay() {
        try {
            const fetchedQuotesRaw = await fetch('https://type.fit/api/quotes');
            const fetchedQuotesJSON = await fetchedQuotesRaw.json(); 
            const randomIdx = getRndInteger(0, 1643); 
            const randomQuote = fetchedQuotesJSON[randomIdx]; 
            
            document.getElementById("quoteDisplay").innerHTML = randomQuote.text;
            document.getElementById("authorDisplay").innerHTML = randomQuote.author;
        }

        catch(err) {

        }
    }
    render() {
        return(
            <div className = "ML_Model_Instructions">
                <div id = "instructionsLM">
                    <p>
                        There are no special instructions for generating new pokémon names, just click on the
                        button below and a new name will be generated by an AI algorithm!
                    </p>
                    <p>
                        While generating names, enjoy the inspirational quotes below :) 
                    </p>
                </div>
                <div id = "quoteBox">
                    <div id = "quoteDisplay"></div>
                    <div id = "authorDisplay"></div>
                    <div id = "newQuote"></div>
                </div>
            </div>
        );
    }
}

export default InstructionsLM; 